<a href="https://colab.research.google.com/github/jardinthee/codetree-TILs/blob/main/6_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

6장_붓꽃 품종 분류, 원 핫 인코딩, 소프트맥스

In [12]:
import pandas as pd
import tensorflow as tf
file_path_iris = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')
iris= pd.get_dummies('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')

In [14]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentrophy',metrics = 'accuracy')

붓꽃을 분류하는 수식을 소프트맥스(softmax)라는 함수로 감싸주면 소프트맥스 함수에 의해 우리가 원하는 0과 1사이의 결과를 받을 수 있게 된다

## **붓꽃 품종 분류 실습**

In [15]:
import tensorflow as tf
import pandas as pd

In [16]:
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [18]:
encoding_iris = pd.get_dummies(iris)
encoding_iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [19]:
print(encoding_iris.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [20]:
indep_v = encoding_iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep_v = encoding_iris[['품종_setosa', '품종_versicolor','품종_virginica']]
print(indep_v.shape, dep_v.shape)

(150, 4) (150, 3)


# 모델 구조 만들기

In [23]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [25]:
model.fit(indep_v,dep_v,epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 2.0617 - accuracy: 0.5400
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 2.0299 - accuracy: 0.5333
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 1.9965 - accuracy: 0.5267
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.9630 - accuracy: 0.5333
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 1.9308 - accuracy: 0.5067
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 1.9006 - accuracy: 0.5067
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 1.8681 - accuracy: 0.5067
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 1.8363 - accuracy: 0.4933
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.8036 - accuracy: 0.5067
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7706 - accuracy: 0.4933
Epoch 11/100
5/5 [===========

In [26]:
model.fit(indep_v,dep_v,epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5947 - accuracy: 0.8467
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5913 - accuracy: 0.8533
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5898 - accuracy: 0.8600
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5858 - accuracy: 0.8600
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5839 - accuracy: 0.8600
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5813 - accuracy: 0.8600
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5781 - accuracy: 0.8600
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5753 - accuracy: 0.8667
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5742 - accuracy: 0.8667
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5698 - accuracy: 0.8600
Epoch 11/100
5/5 [===========

In [27]:
model.fit(indep_v,dep_v,epochs=100,verbose=0)

# 모델을 이용

In [29]:
print(model.predict(indep_v[0:5]))

1/1 [==============================] - 0s 67ms/step
[[0.9576136  0.04079574 0.00159065]
 [0.9219825  0.0745872  0.00343024]
 [0.94640166 0.05109023 0.00250805]
 [0.92768496 0.06786567 0.00444928]
 [0.96337676 0.0351331  0.00149011]]


In [30]:
print(dep_v[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [31]:
print(model.predict(indep_v[-5:]))
print(dep_v[-5:])

1/1 [==============================] - 0s 20ms/step
[[0.00201299 0.37810606 0.6198809 ]
 [0.00292577 0.40040243 0.59667176]
 [0.00361503 0.3772697  0.61911523]
 [0.0020567  0.24538003 0.75256324]
 [0.00531667 0.31190118 0.6827821 ]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [32]:
print(model.get_weights())

[array([[-0.29012227, -0.09603276, -0.9329041 ],
       [ 1.161824  , -0.19843027, -0.19387938],
       [-1.1056064 , -0.16913019,  0.8612093 ],
       [-1.390453  ,  0.4391381 ,  0.9937901 ]], dtype=float32), array([ 0.92437637, -0.13744186, -0.68316853], dtype=float32)]


첫번째 칼럼은 세토사를 판별하는 수식의 가중치들,
두번째 칼럼은 버시컬러인지 아닌지를 판별하는 수식의 가중치들
세번째 칼럼은 버지니카를 판별하는 수식의 가중치들